<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY podstawy

In [ ]:
import numpy as np

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

# 1Dimension Array



In [ ]:
x = np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size #liczba elementów w tablicy

2

In [ ]:
x.dtype #typ danych - ile miejsca zajmują w pamięci

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

#2D Array

In [ ]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

#3D Array

In [ ]:
x = np.array(
    [[[4,3,1],
     [3,1,2]],
    [[4,1,3],
     [4,2,1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape #2 elementy po 2 wiersze po 3 kolumny

(2, 2, 3)

#Typy danych

In [ ]:
#do array można przekazać dodatkowy parametr - dtype, aby kontrolować typ
A = np.array([1, 2.3, 3.3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
#liczby złożone
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1, 2.3, 3.3], dtype='int') #konwersja na liczby całkowite
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24,120,230], dtype=np.int16)
A.dtype

dtype('int16')

In [ ]:
#unsigned int - do 255
A = np.array([24,120,230], dtype=np.uint8)
A.dtype

dtype('uint8')

# Tworzenie tablic


In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5)) #domyślnie float

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10) #jak range w py

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=10) #num - ile chcemy elementów równo rozłożonych w danym przedziale

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(5,-1) #chcemy 3 wiersze i odpowiednią liczbę kolumn

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.reshape(-1,5) #tu nie wskazujemy ile chcemy wierszy, dobierze automatycznie

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#Podstawowe operacje na tablicach

In [ ]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


## Działania przy użyciu znaków:

In [ ]:
A + B

array([6, 0, 7, 4])

In [ ]:
A - B

array([0, 2, 1, 0])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
A / B #w B nie może być 0

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
A - 3

array([ 0, -2,  1, -1])

In [ ]:
2 * A

array([6, 2, 8, 4])

In [ ]:
abs(A-3)

array([0, 2, 1, 1])

## Funkcje do działań na tablicach:

In [ ]:
np.add(A,B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
#Mnożenie macierzowe
x = np.array([[1,3],[-2,1]])
y = np.array([[6,0],[-1,2]])
print(x)
print(y)

[[ 1  3]
 [-2  1]]
[[ 6  0]
 [-1  2]]


In [ ]:
x * y #mnożenie zwykłe

array([[6, 0],
       [2, 2]])

In [ ]:
np.dot(x,y) #mnożenie macierzowe - wiersz razy kolumna, wiersz razy kolumna

array([[  3,   6],
       [-13,   2]])

In [ ]:
#inny sposób na to samo:
x.dot(y)

array([[  3,   6],
       [-13,   2]])

In [ ]:
#mnożenie macierzy nie jest przemienne x*y nie równa się y*x
y.dot(x)

array([[ 6, 18],
       [-5, -1]])

In [ ]:
#3 sposób mnożenia macierzy - @
y @ x

array([[ 6, 18],
       [-5, -1]])

# Generowanie liczb pseudolosowych

In [ ]:
#ziarno losowania - jeżeli chcemy mieć ten sam wynik za każdym razem
np.random.seed(0)

In [ ]:
np.random.randn() #liczby losowe z rozkładu normalnego (randN)

1.764052345967664

In [ ]:
np.random.rand(10) #parametr - ile elementów tablicy

array([0.60276338, 0.54488318, 0.4236548 , 0.64589411, 0.43758721,
       0.891773  , 0.96366276, 0.38344152, 0.79172504, 0.52889492])

In [ ]:
np.random.randn(10,4)
#można użyć do stworzenia przykładowych danych do histogramu rozkładu normalnego
#drugi parametr - liczba kolumn, możemy utożstamiać z liczbą zmiennych,
#pierwszy parametr - liczba wierszy - możemy utożsamiać z liczbą próbek

array([[ 0.40015721,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
#rozkład jednostajny na przedziale
np.random.rand() #przy rand() 0 domknięte, 1 wyłączone z przedziału

0.1965823616800535

In [ ]:
np.random.rand(10,2)


array([[0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145]])

In [ ]:
#przedział domknięty
np.random.randint(10)

2

In [ ]:
np.random.randint(low=10, high=101) #parametr startowy i końcowy - taka kondiguracja - losowa liczba dwucyfrowa

37

In [ ]:
np.random.randint(10,101, 10) #trzeci parametr - ile elementów


array([87, 85, 66, 26, 34, 39, 31, 35, 90, 70])

In [ ]:
np.random.choice([4, 2, 1, 3, 5]) #losowy element z listy

np.int64(2)

In [ ]:
np.random.choice(['python', 'java', 'sql'])

np.str_('sql')

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data) #zmiana w obiekcie stała
data

array([8, 5, 4, 0, 7, 9, 3, 2, 1, 6])

# Podstawowe funkcje

In [ ]:
np.exp(1) #eksponent - od 1 zwraca liczbę Eulera

np.float64(2.718281828459045)

In [ ]:
np.sqrt(9) #pierwiastek kwadratowy

np.float64(3.0)

In [ ]:
np.all([2,3,1]) #jeżeli jakikolwiek element = False -> zwraca False

np.True_

In [ ]:
np.all([-2,3,0])

np.False_

In [ ]:
np.any([2,3,0]) #czy jakikolwiek obiekt jest prawdą, zwraca False, jeżeli są same zera

np.True_

In [ ]:
np.any([0,0,0])

np.False_

In [ ]:
bool(0) #funkcja w py - zwraca False dla 0

False

In [ ]:
A = np.random.rand(5)
A

array([0.65320082, 0.65210327, 0.43141844, 0.8965466 , 0.36756187])

In [ ]:
np.argmax(A) #zwraca indeks największej wartości

np.int64(3)

In [ ]:
A[np.argmax(A)]

np.float64(0.896546595851063)

In [ ]:
np.argmin(A) #zwraca ideks najniższej wartości

np.int64(4)

In [ ]:
np.argsort(A) #oddaje indeksy po kolei rosnąco

array([4, 2, 1, 0, 3])

In [ ]:
np.max(A)

np.float64(0.896546595851063)

In [ ]:
np.min(A)

np.float64(0.36756187004789653)

In [ ]:
np.mean(A)

np.float64(0.6001661982383513)

In [ ]:
np.median(A)

np.float64(0.6521032700016889)

In [ ]:
np.std(A)

np.float64(0.1875804102496216)

# Indeksowanie i wycinanie* tablic
\* wybieranie danych z tablic

In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[indeks lub indeksy], A[start:stop], A[:stop], A[start:] element stop nie wchodzi do listy docelowej
A[2]

np.int64(2)

In [ ]:
A[2:] #wszystkie od 2 do końca

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[[0,2]] #wycinanie konkretnych elementów

array([0, 2])

In [ ]:
#indeksowanie od końca -> -1 zwraca ostatni element
A[-1]

np.int64(19)

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [ ]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[0] #0 pierwszy wiersz, 1 - kolejny

array([0, 1, 2, 3, 4])

In [ ]:
#wybieranie kolumny:
A[:,0]

array([ 0,  5, 10, 15])

In [ ]:
A[:,-1]

array([ 4,  9, 14, 19])

In [ ]:
#porównaj z:
A[:-1]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#konkreny element:
A[1,1] #indeks wiersza, indeks kolumny

np.int64(6)

In [ ]:
A[1:3,1:4] #przedziały - dla wierszy i dla kolumny

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
A[1,2] = 14 #przypisanie nowej wartości do tablicy
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Iteracja po tablicach

In [ ]:
for row in A: #po wierszu
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
  print(row[2])

2
14
12
17


In [ ]:
for item in A.flat: #iterowanie po każdym elemencie tablicy
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


# Zmiana rozmiaru tablic

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.shape

(4, 5)

In [ ]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel() #wypłaszczenie danych

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
print(A)

[[ 0  1  2  3  4]
 [ 5  6 14  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
A.T #transponowanie tablicy tak jak transponowanie macierzy - zamiana wiersza na kolumnę i kolumny na wiersz

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Maski logiczne

In [ ]:
A = np.arange(-10,10,0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
#gdzie mamy wartości ujemne?
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#dzięki masce możemy wyciąć interesujące nas elementy
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
#łączenie warunków
# A[A > -5 and A < 5] tak się nie da
np.bitwise_and(A > -5, A < 5) #zwraca maskę, dzięki której możemy wybrać interesujące nas elementy

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])