<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'2.0.2'

#1. Norma wektora, długość wektora w $R^2 $
${\mathbf {v}}=[v_1,v_2]$

$\left\|{\mathbf {v}}\right\|={\sqrt {v_1^2+v_2^2}}$

$\vec{v}$


In [ ]:
v1 = np.array([0,4])
v1

array([0, 4])

In [ ]:
np.linalg.norm(v1) #liczenie normy w przesterzeni R2

np.float64(4.0)

# 2. Norma euklidesowa w $R^n$
${ \left\| {\mathbf {v}} \right\|} = {\sqrt  {v_{1}^{2}+v_{2}^{2}+ ...+ v_{2}^{n}}}$

uogólnienie normy przestrzeni Rn - długość wektora w przestrzeni Rn - uogólniamy wzór
n współrzędnych podniesionych do kwadratu, zsumowanych i z tego pierwiastek

In [ ]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2) #długość wektora w przestrzeni R3

np.float64(19.209372712298546)

# 3. Odległość dwóch punktów na płaszczyźnie

In [ ]:
p = np.array([3,0]) #ramiona trójkąta prostokątnego Pitagorejskiego
q = np.array([0,4])
np.linalg.norm(p-q)

np.float64(5.0)

# 4. Odległość dwóch punktów w przestrzeni $R^n$
\begin{aligned}
d(\mathbf {q}, \mathbf {p}) = d(\mathbf {p}, \mathbf {q})
&= \sqrt{{(q_1 - p_1)}^2+{(q_2 - p_2)}^2+ \cdots + {(q_n - p_n)}^2}\\
&= \sqrt{\sum_{i=1}^n{(q_i - p_i)}^2}
\end{aligned}


In [ ]:
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p-q)

np.float64(5.0990195135927845)

liczymy normę wekora, który powstaje - pierwiastek sumy kwadratów różnic

# Mnożenie macierzy
$$
{A} =
{\begin{bmatrix}
a_{11}&a_{12}&\cdots &a_{1n}\\
a_{21}&a_{22}&\cdots &a_{2n}\\
\vdots &\vdots &\ddots &\vdots \\
a_{m1}&a_{m2}&\cdots &a_{mn}\\
\end{bmatrix}}
$$
A - macierz wymiaru $m x n$
$$
{B} =
{\begin{bmatrix}
b_{11}&b_{12}&\cdots &b_{1p}\\
b_{21}&b_{22}&\cdots &b_{2p}\\
\vdots &\vdots &\ddots &\vdots \\
b_{n1}&b_{n2}&\cdots &b_{np}\\
\end{bmatrix}}
$$
B - macierz wymiaru $n x p$
$$C = AB$$
C - macierz wymiaru $m\ x\ p$  
Aby móc pomnożyć dwie macierze liczba liczba kolumn w lewej macierzy musi zgadzać się z liczbą wierszy prawej macierzy (tutaj - ten sam parametr n)

Mnożenie macierzy nie jest przemienne! Tzn. $$AB \neq BA$$

##Przykład 1
$X = \begin{bmatrix}5 &3\\3 &9\end{bmatrix}$, $Y= \begin{bmatrix}1\\-1\end{bmatrix} $
$$$$
$X$ macierz 2x2
$$$$
$Y$ macierz 2x1
$$
Z = X \cdot Y = \begin{bmatrix}5 &3\\3 &9\end{bmatrix} \cdot
\begin{bmatrix}1\\-1\end{bmatrix}
=
\begin{bmatrix}2\\-6\end{bmatrix}
$$
$Z$ macierz 2x1

mnożymy wiersz razy kolumny, czyli tutaj ->
najpierw pierwszy wiersz: 5\*1 + 3\*-1 = 2
i drugi: 3\*1 + 9\*-1 = -6

Rozmiar macierzy wynikowej - tyle wierszy, ile w pierwszej macierzy, tyle kolumn, ile w drugiej

In [ ]:
X = np.array([[5,3],[3,9]])
Y = np.array([[1],[-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X,Y) #przy próbie pomnożenia np.dot(Y,X) - błąd, nie zgadzają się wymiary
Z

array([[ 2],
       [-6]])

##Przykład 2
$X = \begin{bmatrix}2 &-1 &3\\3 &1 &0\end{bmatrix}$,
$Y = \begin{bmatrix}2 &1 &-1\\0 &-1 &2\\3 &2 &0\end{bmatrix}$
$$$$
$X$ macierz 2x3
$$$$
$Y$ macierz 3x3
$$
Z = X \cdot Y = \begin{bmatrix}2 &-1 &3\\3 &1 &0\end{bmatrix} \cdot
\begin{bmatrix}2 &1 &-1\\0 &-1 &2\\3 &2 &0\end{bmatrix} =
\begin{bmatrix}13 &9 &-4\\6 &2 &1\end{bmatrix}
$$
$$$$
$Z$ macierz 2x3

In [ ]:
X = np.array([2,-1,3,3,1,0]).reshape(2,3)
Y = np.array([[2,1,-1],[0,-1,2],[3,2,0]])
print(f"{X}\n")
print(Y)

[[ 2 -1  3]
 [ 3  1  0]]

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
Z = np.dot(X,Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

#Wyznacznik macierzy
$$
A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix}
$$
$A$ - macierz wymiaru nxn (macierz kwadratowa stopnia n)

Oznaczenia:
$
|A| =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix}
$ lub det $A = $ det $\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix} $

Przykład:
det - wyznacznik

det $A = \begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} \\
\end{bmatrix} =a_{11}a_{22} - a_{12}a_{21}
$


det $A = \begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
\end{bmatrix} =a_{11}a_{22}a_{33} + a_{21}a_{12}a_{23} + a_{31}a_{12}a_{23}
- a_{21}a_{12}a_{33} - a_{11}a_{32}a_{23} - a_{31}a_{22}a_{13}
$

det $A = \begin{bmatrix}
2 & 4 \\
-1 & 3 \\
\end{bmatrix} =2 \cdot3-4\cdot(-1) = 6+4=10
$

In [3]:
A = np.array([[2,4],[-1,3]])
round(np.linalg.det(A),2)

np.float64(10.0)

#Ślad macierzy
$$
A =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{bmatrix}
$$
$A$ - macierz wymiaru nxn

${\displaystyle \operatorname {tr}(A) = \sum _{i=1}^{n}{a_{ii}=a_{11}+a_{22}+\cdots+ a_{nn}}}$

Przykład:
$
A = \begin{bmatrix}
2 & 4\\
-1 & 3
\end{bmatrix}
$

${\displaystyle \operatorname {tr}(A) = \sum _{i=1}^{2}a_{ii}=a_{11}+a_{22}=2+3=5}$


In [4]:
A = np.array([[2,4],[-1,3]])
np.trace(A)

np.int64(5)

#Macierz jednostkowa
Macierz jednostkowa - macierz kwadratowa, któej współczynniki podane są wzorem:

$${a_{ij}={\begin{cases}1\quad {\text{dla}}\quad i=j\\[2pt]0\quad {\text{dla}}\quad i\neq j\end{cases}}}$$
(współczynniki na przekątnej są równe 1)

Przykłady

${I_{1}={\begin{bmatrix}1\end{bmatrix}},\;I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\;I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}}}$


In [5]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#Macierz odwrotna
$A$ - macierz kwadratowa stopnia $n$. (Macierze inne niż kwadratowe nie mają macierzy odwrotnych).
Macierz $A$ posiada macierz odwrotną, gdy istnieje macierz $B$, taka, że
$$AB=BA=I$$
(pomnożenie A razy B, jak i B raz A ma dawać macierz jednostkową - I - element neutralny mnożenia macierzy - nie zmienia mnożenia)

$
A = \begin{bmatrix}
2&4\\
-1&3
\end{bmatrix}
$

In [12]:
A = np.array([[2,4],[-1,3]])
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [13]:
np.set_printoptions(precision=4,suppress=True) #ustawienie dla printów - supress True - bez notacji matematycznej
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [14]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

#Macierz transponowana
Zamiana wierszy na kolumny i kolumny na wiersze.
#### Przykład 1:

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&-1\\4&3\end{bmatrix}$

#### Przykład 2:
$A = \begin{bmatrix}2&1&-1\\0&-1&2\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&0\\1&-1\\-1&2\end{bmatrix}$


In [15]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [16]:
A.T

array([[ 2, -1],
       [ 4,  3]])

#Rozwiązywanie układów równań
Rozważmy układ równań $U$:
$${\displaystyle \mathrm {U} \colon {\begin{cases}{\begin{matrix}a_{11}x_{1}&+&a_{12}x_{2}&+&\dots &+&a_{1n}x_{n}&=b_{1},\\a_{21}x_{1}&+&a_{22}x_{2}&+&\dots &+&a_{2n}x_{n}&=b_{2},\\\vdots &&\vdots &&\ddots &&\vdots &\vdots \\a_{m1}x_{1}&+&a_{m2}x_{2}&+&\dots &+&a_{mn}x_{n}&=b_{m}.\end{matrix}}\end{cases}}.}$$

a - współczynniki
x - niewiadome
b - wyrazy wolne

Wykorzystując macierze, możemy to przedtsawić następująco:

rozdzielamy współczynniki, wektor niewiadomych oraz wektor wyrazów wolnych:

$$
\begin{bmatrix}
a_{11} & a_{12} &\cdots & a_{1n}\\
a_{21} & a_{22} &\cdots & a_{2n}\\
\vdots & \vdots &\ddots & \vdots\\
a_{m1} & a_{m2} &\cdots & a_{mn}\\
\end{bmatrix}
\begin{bmatrix}x_{1}\\x_{2}\\\vdots\\x_{n}\end{bmatrix}=
\begin{bmatrix}b_{1}\\b_{2}\\\vdots\\b_{m}\end{bmatrix}
$$
I w zapisie skrótowym:
$$\mathbf {AX} =\mathbf {B}$$

Gdzie:  
$A = {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}$ - macierz współczynników

${\displaystyle \mathbf {B} =[b_{1},b_{2},\dots ,b_{m}]} $ - wektor wyrazów wolnych  
${\mathbf  X}=[x_{1},x_{2},\dots ,x_{n}] $ - wektor niewiadomych

Jeśli macierz układu $A$ jest macierzą kwadratową, to oznaczoność układu jest równoważna jej odwracalności, tzn.
$$\mathbf {AX} =\mathbf {B}$$
$${\displaystyle \mathbf {A} ^{-1}\mathbf {AX} =\mathbf {A} ^{-1}\mathbf {B}} $$
$$\mathbf {X} =\mathbf {A} ^{-1}\mathbf {B} .$$

Aby rozwiązać równanie, musimy znaleźć macierz odwrotną do macierzy A i pomnożyć ją przez wektor wyrazów wolnych B.


#### Przykład:
Rozważmy układ równań:
$$\begin{cases}2x + 4y = 10 \\ x - y = -1 \end{cases}$$  
Rozwiązaniem jest para liczb:
$$\begin{cases}x = 1 \\ y = 2 \end{cases}$$  


In [4]:
A = np.array([[2,4],[1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [5]:
B = np.array([[10],[-1]])
print(B)

[[10]
 [-1]]


In [6]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv,B)
X

array([[1.],
       [2.]])

In [7]:
X.shape

(2, 1)