<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

#1. Norma wektora, długość wektora w $R^2 $
${\mathbf {v}}=[v_1,v_2]$

$\left\|{\mathbf {v}}\right\|={\sqrt {v_1^2+v_2^2}}$

$\vec{v}$


In [ ]:
v1 = np.array([0,4])
v1

array([0, 4])

In [ ]:
np.linalg.norm(v1) #liczenie normy w przesterzeni R2

np.float64(4.0)

# 2. Norma euklidesowa w $R^n$
${ \left\| {\mathbf {v}} \right\|} = {\sqrt  {v_{1}^{2}+v_{2}^{2}+ ...+ v_{2}^{n}}}$

uogólnienie normy przestrzeni Rn - długość wektora w przestrzeni Rn - uogólniamy wzór
n współrzędnych podniesionych do kwadratu, zsumowanych i z tego pierwiastek

In [ ]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2) #długość wektora w przestrzeni R3

np.float64(19.209372712298546)

# 3. Odległość dwóch punktów na płaszczyźnie

In [ ]:
p = np.array([3,0]) #ramiona trójkąta prostokątnego Pitagorejskiego
q = np.array([0,4])
np.linalg.norm(p-q)

np.float64(5.0)

# 4. Odległość dwóch punktów w przestrzeni $R^n$
\begin{aligned}
d(\mathbf {q}, \mathbf {p}) = d(\mathbf {p}, \mathbf {q})
&= \sqrt{{(q_1 - p_1)}^2+{(q_2 - p_2)}^2+ \cdots + {(q_n - p_n)}^2}\\
&= \sqrt{\sum_{i=1}^n{(q_i - p_i)}^2}
\end{aligned}


In [ ]:
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p-q)

np.float64(5.0990195135927845)

liczymy normę wekora, który powstaje - pierwiastek sumy kwadratów różnic

# Mnożenie macierzy
$$
{A} =
{\begin{bmatrix}
a_{11}&a_{12}&\cdots &a_{1n}\\
a_{21}&a_{22}&\cdots &a_{2n}\\
\vdots &\vdots &\ddots &\vdots \\
a_{m1}&a_{m2}&\cdots &a_{mn}\\
\end{bmatrix}}
$$
A - macierz wymiaru $m x n$
$$
{B} =
{\begin{bmatrix}
b_{11}&b_{12}&\cdots &b_{1p}\\
b_{21}&b_{22}&\cdots &b_{2p}\\
\vdots &\vdots &\ddots &\vdots \\
b_{n1}&b_{n2}&\cdots &b_{np}\\
\end{bmatrix}}
$$
B - macierz wymiaru $n x p$
$$C = AB$$
C - macierz wymiaru $m\ x\ p$  
Aby móc pomnożyć dwie macierze liczba liczba kolumn w lewej macierzy musi zgadzać się z liczbą wierszy prawej macierzy (tutaj - ten sam parametr n)

Mnożenie macierzy nie jest przemienne! Tzn. $$AB \neq BA$$

##Przykład 1
$X = \begin{bmatrix}5 &3\\3 &9\end{bmatrix}$, $Y= \begin{bmatrix}1\\-1\end{bmatrix} $
$$$$
$X$ macierz 2x2
$$$$
$Y$ macierz 2x1
$$
Z = X \cdot Y = \begin{bmatrix}5 &3\\3 &9\end{bmatrix} \cdot
\begin{bmatrix}1\\-1\end{bmatrix}
=
\begin{bmatrix}2\\-6\end{bmatrix}
$$
$Z$ macierz 2x1

mnożymy wiersz razy kolumny, czyli tutaj ->
najpierw pierwszy wiersz: 5\*1 + 3\*-1 = 2
i drugi: 3\*1 + 9\*-1 = -6

Rozmiar macierzy wynikowej - tyle wierszy, ile w pierwszej macierzy, tyle kolumn, ile w drugiej

In [ ]:
X = np.array([[5,3],[3,9]])
Y = np.array([[1],[-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X,Y) #przy próbie pomnożenia np.dot(Y,X) - błąd, nie zgadzają się wymiary
Z

array([[ 2],
       [-6]])

##Przykład 2
$X = \begin{bmatrix}2 &-1 &3\\3 &1 &0\end{bmatrix}$,
$Y = \begin{bmatrix}2 &1 &-1\\0 &-1 &2\\3 &2 &0\end{bmatrix}$
$$$$
$X$ macierz 2x3
$$$$
$Y$ macierz 3x3
$$
Z = X \cdot Y = \begin{bmatrix}2 &-1 &3\\3 &1 &0\end{bmatrix} \cdot
\begin{bmatrix}2 &1 &-1\\0 &-1 &2\\3 &2 &0\end{bmatrix} =
\begin{bmatrix}13 &9 &-4\\6 &2 &1\end{bmatrix}
$$
$$$$
$Z$ macierz 2x3

In [ ]:
X = np.array([2,-1,3,3,1,0]).reshape(2,3)
Y = np.array([[2,1,-1],[0,-1,2],[3,2,0]])
print(f"{X}\n")
print(Y)

[[ 2 -1  3]
 [ 3  1  0]]

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
Z = np.dot(X,Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])