<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [2]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [3]:
price.sum() #suma wszystkich elementów w tablicy

np.float64(4650.1)

In [4]:
#suma w każdym wierszu lub kolumnie - parametr, po której osi liczyć 0 - suma poszczególnych kolumn, 1 - wierszy
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [5]:
price.sum(axis=1)


array([1049.7, 2049.4, 1551. ])

In [10]:
np.sum(price, axis=0) #inny sposób na to samo

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [11]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [13]:
np.max(price)

np.float64(2000.0)

In [14]:
np.median(price, axis=0)

array([  12.4,   13. ,   11.9,   12.6, 1500. ])

In [15]:
np.mean(price, axis = 0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

In [16]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

In [23]:
np.set_printoptions(precision=4,suppress=True) #ustawienie dla printów - supress True - bez notacji matematycznej

In [24]:

np.var(price, axis = 0)

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])