<a href="https://colab.research.google.com/github/JotJaw/data-science-bootcamp/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello Colab")

Hello Colab


NUMPY Podstawy

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1Dimension Array

In [6]:
x = np.array([1,3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [11]:
x.shape

(2,)

In [12]:
x.size #liczba elementów w tablicy

2

In [14]:
x.dtype #typ danych - ile miejsca zajmują w pamięci

dtype('int64')

In [16]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [18]:
x.dtype

dtype('float64')

2D Array

In [20]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [22]:
x.ndim

2

In [23]:
x.shape

(2, 2)

In [24]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [25]:
x.shape

(2, 3)

3D Array

In [27]:
x = np.array(
    [[[4,3,1],
     [3,1,2]],
    [[4,1,3],
     [4,2,1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [28]:
x.ndim

3

In [29]:
x.shape #2 elementy po 2 wiersze po 3 kolumny

(2, 2, 3)

Typy danych

In [30]:
#do array można przekazać dodatkowy parametr - dtype, aby kontrolować typ
A = np.array([1, 2.3, 3.3], dtype='float')
A.dtype

dtype('float64')

In [31]:
#liczby złożone
A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [32]:
A = np.array([1, 2.3, 3.3], dtype='int') #konwersja na liczby całkowite
A.dtype

dtype('int64')

In [33]:
A

array([1, 2, 3])

In [34]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [36]:
A = np.array([24,120,230], dtype=np.int16)
A.dtype

dtype('int16')

In [37]:
#unsigned int - do 255
A = np.array([24,120,230], dtype=np.uint8)
A.dtype

dtype('uint8')